<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/index/index">首页</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">首页</li>
    </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            仪表盘
            <small>
                <i class="icon-double-angle-right"></i>
                系统信息
            </small>
        </h1>
    </div><!--/.page-header-->

    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->

            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box transparent">
                        <div class="widget-header widget-header-flat">
                            <h4 class="lighter">
                                <i class="icon-rss orange"></i>
                                Information
                            </h4>

                            <div class="widget-toolbar">
                                <a href="#" data-action="collapse">
                                    <i class="icon-chevron-up"></i>
                                </a>
                            </div>
                        </div>

                        <div class="widget-body">
                            <div class="widget-main no-padding">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th width="10%">
                                            <i class="icon-caret-right blue"></i>
                                            NAME
                                        </th>

                                        <th>
                                            <i class="icon-caret-right blue"></i>
                                            MESSAGE
                                        </th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <tr>
                                        <td>OS</td>
                                        <td>
                                            <b class="green"><?=PHP_OS?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Server IP</td>
                                        <td>
                                            <b class="green"><?= GetHostByName($_SERVER['SERVER_NAME'])?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>PHP Version</td>
                                        <td>
                                            <b class="green"><?=PHP_VERSION?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Nginx</td>
                                        <td>
                                            <b class="green"><?=$_SERVER['SERVER_SOFTWARE']?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Upload max filesize</td>
                                        <td>
                                            <b class="green"><?=get_cfg_var("upload_max_filesize")?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Max execution time</td>
                                        <td>
                                            <b class="green"><?=get_cfg_var("max_execution_time")."秒 "?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Memory limit for script run</td>
                                        <td>
                                            <b class="green"><?=get_cfg_var ("memory_limit")?></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Server system time</td>
                                        <td>
                                            <b class="green"><?=date("Y-m-d G:i:s")?></b>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div><!--/widget-main-->
                        </div><!--/widget-body-->
                    </div><!--/widget-box-->
                </div>
            </div>

            <div class="hr hr8 hr-double hr-dotted"></div>

            <div class="hr hr8 hr-double hr-dotted" style="margin-top: 18%;"></div>

            <div class="row-fluid">
                <div class="span12 pull-left" style="text-align: center; color:#989898"> Copyright © 2017-2018 <a href="https://www.tm51.com" target="_blank">童梦无忧社区(https://www.tm51.com)</a> 版权所有 All Rights Reserved 鄂ICP备12015582号-4 </div>
            </div>

            <!--PAGE CONTENT ENDS-->
        </div><!--/.span-->
    </div><!--/.row-fluid-->
</div><!--/.page-content-->
