<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>砍价--管理系统</title>
    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<!--basic styles-->
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/common.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/bootstrap.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/bootstrap-responsive.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/font-awesome.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/font-awesome-ie7.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/ace-ie.min.css"/>
<!--page specific plugin styles-->
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/ace.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/ace-responsive.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/ace-skins.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/datepicker.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/daterangepicker.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/bootstrap-datetimepicker.min.css"/>
<link rel="stylesheet" href="<?= constant('BASE_URL') ?>/ace/assets/css/chosen.css"/>
<!--basic scripts-->
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery-2.0.3.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/bootstrap.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/ace-elements.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/ace.min.js"></script>
<!--page specific plugin scripts-->
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/excanvas.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.dataTables.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.dataTables.bootstrap.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.slimscroll.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.easy-pie-chart.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.sparkline.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/flot/jquery.flot.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/flot/jquery.flot.pie.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/flot/jquery.flot.resize.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/date-time/bootstrap-datepicker.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/date-time/daterangepicker.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/date-time/moment.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/bootbox.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/jquery.fileupload.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/chosen.jquery.min.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/emoji.js"></script>
<script src="<?= constant('BASE_URL') ?>/ace/assets/js/emojiList.js"></script>
<script src="<?= constant('BASE_URL')?>/ace/assets/js/layer/layer.js" type="text/javascript" charset="utf-8"></script>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a href="/admin/index/index" class="brand">
                <small>
                    <i class="icon-leaf"></i>
                    Tm Admin
                </small>
            </a><!--/.brand-->

            <ul class="nav ace-nav pull-right">

                <li class="green">
                    <a href="/admin/aec/post">
                    </a>
                </li>

                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="/ace/assets/avatars/avatar.png"
                             alt="Jason's Photo"/>
                        <span class="user-info">
                            <small>Welcome</small>
                            <?= $_SESSION['admin_info']['name']; ?>
                        </span>
                        <i class="icon-caret-down"></i>
                    </a>

                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
                        <li>
                            <a href="/admin/auth/admin">
                                <i class="icon-user"></i>
                                账号管理
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a id="logout" href="/admin/login/logout">
                                <i class="icon-off"></i>
                                退出
                            </a>
                        </li>
                    </ul>
                </li>
            </ul><!--/.ace-nav-->
        </div><!--/.container-fluid-->
    </div><!--/.navbar-inner-->
</div>

<div class="main-container container-fluid">
    <a class="menu-toggler" id="menu-toggler" href="#">
        <span class="menu-text"></span>
    </a>

    <div class="sidebar" id="sidebar">
        <div class="sidebar-shortcuts" id="sidebar-shortcuts">
            <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
                <a href="/admin/thread/thread">
                    <button class="btn btn-small btn-success">
                        <i class="icon-list"></i>
                    </button>
                </a>
                <a href="/admin/diary/diary">
                    <button class="btn btn-small btn-info">
                        <i class="icon-calendar"></i>
                    </button>
                </a>
                <a href="/admin/post/post">
                    <button class="btn btn-small btn-warning">
                        <i class="icon-comment"></i>
                    </button>
                </a>
                <a href="/admin/user/user">
                    <button class="btn btn-small btn-danger">
                        <i class="icon-group"></i>
                    </button>
                </a>
            </div>
        </div><!--#sidebar-shortcuts-->

        <ul class="nav nav-list" id="nav-list">
            <?php foreach ($_SESSION['admin_nav'] as $access):?>
                <li>
                    <a href="<?=$access['action']?>" class="dropdown-toggle">
                        <i class="<?=$access['icon']?>"></i>
                        <span class="menu-text"><?=$access['title']?></span>
                        <?php if(!empty($access['children'])):?>
                            <b class="arrow icon-angle-down"></b>
                        <?php endif;?>
                    </a>
                    <?php if(!empty($access['children'])):?>
                        <ul class="submenu">
                            <?php foreach ($access['children'] as $children):?>
                                <li>
                                    <a href="<?=$children['action']?>">
                                        <i class="icon-double-angle-right"></i>
                                        <?=$children['title']?>
                                    </a>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    <?php endif;?>
                </li>
            <?php endforeach;?>
        </ul><!--/.nav-list-->

        <div class="sidebar-collapse" id="sidebar-collapse">
            <i class="icon-double-angle-left"></i>
        </div>
    </div>

    <!-- start /.main-content-->
    <div class="main-content">
        <?= $content; ?>
    </div>
    <!-- end /.main-content-->

</div><!--/.main-container-->
<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>
<!--inline scripts related to this page-->
<script type="text/javascript">
    $(function () {
        $(".emoji").emoji();
        // left menu bar storage
        $('.nav-list a[href]').on('click', function () {
            sessionStorage.setItem('nav', $(this).attr('href'));
        });
        $('.sidebar-shortcuts a[href]').on('click', function () {
            sessionStorage.setItem('nav', $(this).attr('href'));
        });
        $('.ace-nav a[href]').on('click', function () {
            sessionStorage.setItem('nav', $(this).attr('href'));
        });
        if (sessionStorage.getItem('nav')) {
            $('.nav-list a[href=\'' + sessionStorage.getItem('nav') + '\']').parents('li').addClass('active').parents('ul').siblings('a').css('display', 'block');
        } else {
            $('.nav-list .dashboard').addClass('active');
        }
        $('#logout').on('click', function () {
            sessionStorage.removeItem('nav');
        });

        $('.easy-pie-chart.percentage').each(function () {
            var $box = $(this).closest('.infobox');
            var barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');
            var trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';
            var size = parseInt($(this).data('size')) || 50;
            $(this).easyPieChart({
                barColor: barColor,
                trackColor: trackColor,
                scaleColor: false,
                lineCap: 'butt',
                lineWidth: parseInt(size / 10),
                animate: /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,
                size: size
            });
        })

        $('.sparkline').each(function () {
            var $box = $(this).closest('.infobox');
            var barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';
            $(this).sparkline('html', {
                tagValuesAttribute: 'data-values',
                type: 'bar',
                barColor: barColor,
                chartRangeMin: $(this).data('min') || 0
            });
        });


        var placeholder = $('#piechart-placeholder').css({'width': '90%', 'min-height': '150px'});
        var data = [
            {label: "social networks", data: 38.7, color: "#68BC31"},
            {label: "search engines", data: 24.5, color: "#2091CF"},
            {label: "ad campaings", data: 8.2, color: "#AF4E96"},
            {label: "direct traffic", data: 18.6, color: "#DA5430"},
            {label: "other", data: 10, color: "#FEE074"}
        ]

        function drawPieChart(placeholder, data, position) {
            $.plot(placeholder, data, {
                series: {
                    pie: {
                        show: true,
                        tilt: 0.8,
                        highlight: {
                            opacity: 0.25
                        },
                        stroke: {
                            color: '#fff',
                            width: 2
                        },
                        startAngle: 2
                    }
                },
                legend: {
                    show: true,
                    position: position || "ne",
                    labelBoxBorderColor: null,
                    margin: [-30, 15]
                }
                ,
                grid: {
                    hoverable: true,
                    clickable: true
                }
            })
        }

        drawPieChart(placeholder, data);

        /**
         we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically
         so that's not needed actually.
         */
        placeholder.data('chart', data);
        placeholder.data('draw', drawPieChart);


        var $tooltip = $("<div class='tooltip top in hide'><div class='tooltip-inner'></div></div>").appendTo('body');
        var previousPoint = null;

        placeholder.on('plothover', function (event, pos, item) {
            if (item) {
                if (previousPoint != item.seriesIndex) {
                    previousPoint = item.seriesIndex;
                    var tip = item.series['label'] + " : " + item.series['percent'] + '%';
                    $tooltip.show().children(0).text(tip);
                }
                $tooltip.css({top: pos.pageY + 10, left: pos.pageX + 10});
            } else {
                $tooltip.hide();
                previousPoint = null;
            }

        });


        var d1 = [];
        for (var i = 0; i < Math.PI * 2; i += 0.5) {
            d1.push([i, Math.sin(i)]);
        }

        var d2 = [];
        for (var i = 0; i < Math.PI * 2; i += 0.5) {
            d2.push([i, Math.cos(i)]);
        }

        var d3 = [];
        for (var i = 0; i < Math.PI * 2; i += 0.2) {
            d3.push([i, Math.tan(i)]);
        }


        var sales_charts = $('#sales-charts').css({'width': '100%', 'height': '220px'});
        $.plot("#sales-charts", [
            {label: "Domains", data: d1},
            {label: "Hosting", data: d2},
            {label: "Services", data: d3}
        ], {
            hoverable: true,
            shadowSize: 0,
            series: {
                lines: {show: true},
                points: {show: true}
            },
            xaxis: {
                tickLength: 0
            },
            yaxis: {
                ticks: 10,
                min: -2,
                max: 2,
                tickDecimals: 3
            },
            grid: {
                backgroundColor: {colors: ["#fff", "#fff"]},
                borderWidth: 1,
                borderColor: '#555'
            }
        });


        $('#recent-box [data-rel="tooltip"]').tooltip({placement: tooltip_placement});

        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('.tab-content')
            var off1 = $parent.offset();
            var w1 = $parent.width();

            var off2 = $source.offset();
            var w2 = $source.width();

            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
            return 'left';
        }


        $('.dialogs,.comments').slimScroll({
            height: '300px'
        });


        //Android's default browser somehow is confused when tapping on label which will lead to dragging the task
        //so disable dragging when clicking on label
        var agent = navigator.userAgent.toLowerCase();
        if ("ontouchstart" in document && /applewebkit/.test(agent) && /android/.test(agent))
            $('#tasks').on('touchstart', function (e) {
                var li = $(e.target).closest('#tasks li');
                if (li.length == 0) return;
                var label = li.find('label.inline').get(0);
                if (label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation();
            });

        $('#tasks').sortable({
                opacity: 0.8,
                revert: true,
                forceHelperSize: true,
                placeholder: 'draggable-placeholder',
                forcePlaceholderSize: true,
                tolerance: 'pointer',
                stop: function (event, ui) {//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved
                    $(ui.item).css('z-index', 'auto');
                }
            }
        );
        $('#tasks').disableSelection();
        $('#tasks input:checkbox').removeAttr('checked').on('click', function () {
            if (this.checked) $(this).closest('li').addClass('selected');
            else $(this).closest('li').removeClass('selected');
        });
    })

    // page jump
    function jump(t) {
        var page = $('.jump-page').val();
        if (page == '') {
            return false;
        }
        var url = t.attr('jump-url');
        location.href = url.substring(0, url.length - 4) + page;
    }

    $('#datetimepicker').datetimepicker({
        format: 'yyyy-mm-dd hh:ii'
    });

    $('#datetimepicker-1').datetimepicker({
        format: 'yyyy-mm-dd hh:ii'
    });

    $('#datetimepicker-2').datetimepicker({
        format: 'yyyy-mm-dd hh:ii'
    });
</script>
</body>
</html>
