<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/index/index">首页</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li>
            <a href="/admin/auth/admin">权限管理</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">编辑添加</li>
    </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            <small>
                <i class="icon-list"></i>
                编辑添加
            </small>
        </h1>
    </div><!--/.page-header-->
    <div class="row-fluid">

        <?php if(!empty($errors)):?>
            <?php foreach($errors as $error):?>
                <div class="alert alert-block alert-error">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <?=$error[0]?>
                </div>
            <?php endforeach;?>
        <?php endif;?>

        <div class="span12">

            <form class="form-horizontal" action="/admin/auth/authAdd" method="post">


                <div class="control-group">
                    <label class="control-label">所属父级</label>
                    <div class="controls">
                        <select name="pid">
                            <?php foreach ($all_auth as $val): ?>
                                    <option  value="<?=$val['id'];?>" <?php if ($val['id'] == $pid):?> selected <?php endif; ?>><?=$val['level'];?><?=$val['title'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">权限名</label>
                    <div class="controls">
                        <input name="title" value="" placeholder="权限名" type="text">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">地址</label>
                    <div class="controls">
                        <input name="action" value="" placeholder="地址" type="text">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">icon</label>
                    <div class="controls">
                        <input name="icon" value="" placeholder="icon" type="text">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">排序</label>
                    <div class="controls">
                        <input name="sort" value="0" placeholder="排序" type="number" min='0'>
                    </div>
                </div>


                <div class="form-actions" style="background-color: #FFFFFF">
                    <button class="btn btn-info" type="submit">
                        <i class="icon-ok bigger-110"></i>
                        提交
                    </button>
                </div>
            </form>

        </div><!--/.span-->
    </div>
</div><!--/.row-fluid-->
<script>
    $('[data-rel=tooltip]').tooltip({container: 'body'});
    $('[data-rel=popover]').popover({container: 'body'});

    $('#id-input-image').fileupload({
        url: '/index/upload/image',
        dataType: 'json',
        formData:{image_type:3},
        done: function(e, res) {
            console.log(res.result);
            if (res.result.code == 0) {
                $('#input-path').val(res.result.data.path);
                $('#input-path-img').attr('src', res.result.data.url);
                $('#input-path-img').parent('div').show();
            } else {
                bootbox.alert(res.message);
            }
        }
    });
</script>
