<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/index/index">首页</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li>
            <a href="/admin/auth/deedadmin">系统管理</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">管理员操作日志</li>
    </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            <small>
                <i class="icon-list"></i>
                管理员操作日志表
            </small>

            <a href="/admin/auth/deedadmin">
                <button class="btn btn-sm btn-info" style="float: right; border-radius: 3px;">
                    <i class="icon-plus"></i>
                </button>
            </a>
        </h1>
    </div><!--/.page-header-->
    <div class="widget-box">
        <div class="widget-header widget-header-small">
            <h5 class="lighter">搜索</h5>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <form class="form-search" action="/admin/auth/deedadmin" method="get">
                    <div class="row-fluid">
                        <label style="margin-right: 2%;">
                            <p>关键词：</p>
                            <input name="keyword"
                                   value="<?php echo (isset($search['keyword'])) ? $search['keyword'] :''; ?>"
                                   placeholder="管理员名字/管理员ID/帖子ID" type="text">
                        </label>
                        <label style="margin-right: 2%;">
                            <p>信息状态：</p>
                            <select name="action">
                                <option value="-2">请选择...</option>
                                <option value="1"
                                    <?php echo (isset($search['action']) && $search['action'] == 1) ? 'selected' : ''; ?>
                                >审核通过
                                </option>
                                <option value="2"
                                    <?php echo (isset($search['action']) && $search['action'] == 2) ? 'selected' : ''; ?>
                                >审核拒绝
                                </option>
                                <option value="3"
                                    <?php echo (isset($search['action']) && $search['action'] == 3) ? 'selected' : ''; ?>
                                >恢复帖子
                                </option>
                                <option value="4"
                                    <?php echo (isset($search['action']) && $search['action'] == 4) ? 'selected' : ''; ?>
                                >删除帖子
                                </option>
                                <option value="5"
                                    <?php echo (isset($search['action']) && $search['action'] == 5) ? 'selected' : ''; ?>
                                >编辑帖子
                                </option>
                            </select>
                        </label>
                        <label style="margin-right: 2%;">
                            <p>操作类型：</p>
                            <select name="type">
                                <option value="-2">请选择...</option>
                                <option value="1"
                                    <?php echo (isset($search['type']) && $search['type'] == 1) ? 'selected' : ''; ?>
                                >帖子
                                </option>
                                <option value="2"
                                    <?php echo (isset($search['type']) && $search['type'] == 2) ? 'selected' : ''; ?>
                                >日记
                                </option>
                                <option value="3"
                                    <?php echo (isset($search['type']) && $search['type'] == 3) ? 'selected' : ''; ?>
                                >评论
                                </option>
                            </select>
                        </label>

                        <label style="margin-right:1%; margin-top: 34px; float: right;">
                            <button type="submit" class="btn btn-inverse btn-small">
                                搜索
                                <i class="icon-search icon-on-right bigger-110"></i>
                            </button>
                        </label>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->

            <div class="row-fluid">
                <div class="span12">
                    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>管理员ID</th>
                            <th>管理员</th>
                            <th>帖子ID</th>
                            <th>操作类型</th>
                            <th>操作内容</th>
                            <th><i class="icon-time bigger-110 hidden-phone"></i>操作时间</th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php foreach($data as $item):?>
                            <tr>

                                <td><?=$item['id']?></td>
                                <td><?=$item['aid']?></td>
                                <th><?=$item['name']?></th>
                                <th><?=$item['target_id']?></th>
                                <td>
                                    <?php if ($item['type'] == 1): ?>
                                        <span class="label label-success arrowed-in arrowed-in-right">帖子</span>
                                    <?php elseif ($item['type'] == 2): ?>
                                        <span class="label label-info arrowed-right arrowed-in">日记</span>
                                    <?php elseif ($item['type'] == 3): ?>
                                        <span class="label label-warning arrowed arrowed-right">评论</span>
                                    <?php endif; ?>
                                </td>

                                <td>
                                    <?php if ($item['action'] == 1): ?>
                                        <span class="label label-info arrowed-right arrowed-in">审核通过</span>
                                    <?php elseif ($item['action'] == 2): ?>
                                        <span class="label label-warning arrowed arrowed-right">审核拒绝</span>
                                    <?php elseif ($item['action'] == 3): ?>
                                        <span class="label label-danger arrowed">恢复帖子</span>
                                    <?php elseif ($item['action'] == 4): ?>
                                        <span class="label arrowed">删除帖子</span>
                                    <?php elseif ($item['action'] == 5): ?>
                                        <span class="label label-info arrowed-right arrowed-in">编辑帖子</span>
                                    <?php endif; ?>
                                </td>
                                <td><?=$item['created_at']?></td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                    <!--pagination-->
                    <div class="pagination" style="float: right">
                        <?=$page_html;?>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/.row-fluid-->
</div><!--/.page-content-->