<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/index/index">首页</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li>
            <a href="/admin/auth/role">角色管理</a>
            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">角色列表</li>
    </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            <small>
                <i class="icon-list"></i>
                角色列表
            </small>
            <?php if ($is_admin):?>
            <a href="/admin/auth/roleAdd">
                <button class="btn btn-sm btn-info" style="float: right; border-radius: 3px;">
                    <i class="icon-plus"></i>
                </button>
            </a>
            <?php endif; ?>
        </h1>
    </div><!--/.page-header-->
    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->

            <div class="row-fluid">
                <div class="span12">
                    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th class="center">
                                <label>
                                    <input type="checkbox"/>
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th>ID</th>
                            <th>角色</th>
                            <th>描述</th>
                            <th>
                                <i class="icon-time bigger-110 hidden-phone"></i>
                                添加时间
                            </th>
                            <th>管理</th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php foreach($data as $item):?>
                        <tr>
                            <td class="center">
                                <label>
                                    <input type="checkbox" name="id" value="<?=$item['id']?>"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?=$item['id']?></td>
                            <td><?=$item['name']?></td>
                            <td><?=$item['describe']?></td>
                            <td><?=$item['created_at']?></td>
                            <!--<td>
                                <div class="hidden-phone visible-desktop btn-group">
                                    <button onclick="roleEdit(<?/*=$item['id']*/?>)" class="btn btn-mini btn-info"
                                            data-rel="tooltip" data-original-title="编辑">
                                        <i class="icon-pencil bigger-120"></i>
                                    </button>
                                </div>
                            </td>-->
                            <td>
                                <?php if ($is_admin):?>
                                <div class="hidden-phone visible-desktop btn-group">
                                    <button onclick="roleAuthEdit(<?=$item['id']?>)" class="btn btn-mini btn-success"
                                            data-rel="tooltip" data-original-title="权限">
                                        <i class="icon-pencil bigger-120"></i>
                                    </button>
                                </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                    <?php if ($is_admin):?>
                    <div style="float: left;">
                        <button class="btn btn-small btn-danger" onclick="confirm('确认删除？') ? roleDel() : false;">
                            删除
                        </button>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div><!--/.row-fluid-->
</div><!--/.page-content-->
<script type="text/javascript">
    $(function () {

        $('table th input:checkbox').on('click', function () {
            var that = this;
            $(this).closest('table').find('tr > td:first-child input:checkbox').each(function () {
                this.checked = that.checked;
                $(this).closest('tr').toggleClass('selected');
            });
        });

        $('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});

        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('table')
            var off1 = $parent.offset();
            var w1 = $parent.width();
            var off2 = $source.offset();
            var w2 = $source.width();
            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
            return 'left';
        }
    });

    function roleDel() {
        var ids = $("input:checkbox[name='id']:checked").map(function (index, ele) {
            return $(ele).val();
        }).get().join(",");
        if (ids == '') {
            bootbox.alert('请先选择...');
            return false
        }
        $.ajax({
            type: "post",
            url: "/admin/auth/roleDel",
            data: {
                id: ids,
                status: status,
            },
            success: function (res) {
                if (res.code == 0) {
                    bootbox.alert(res.message);
                    setTimeout(function () {
                        window.location.href = window.location.href
                    }, 1500);
                } else {
                    bootbox.alert(res.message);
                }
            }
        })
    }

    function roleEdit(id) {
        window.location.href = '/admin/auth/adminEdit?id=' + id;
    }

    function roleAuthEdit(id) {
        window.location.href = '/admin/auth/roleAuthEdit?id=' + id;
    }
</script>