<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>砍价后台--管理系统</title>
    <meta name="description" content="User login page"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--inline styles related to this page-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!--basic styles-->
    <link href="<?=constant('BASE_URL')?>/ace/assets/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="<?=constant('BASE_URL')?>/ace/assets/css/bootstrap-responsive.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/font-awesome.min.css"/>
    <!--[if IE 7]>
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/font-awesome-ie7.min.css"/>
    <![endif]-->
    <!--page specific plugin styles-->
    <!--fonts-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300"/>
    <!--ace styles-->
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/ace.min.css"/>
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/ace-responsive.min.css"/>
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/ace-skins.min.css"/>
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="<?=constant('BASE_URL')?>/ace/assets/css/ace-ie.min.css"/>
    <![endif]-->
</head>

<body class="login-layout">
<div class="main-container container-fluid">
    <div class="main-content">
        <div class="row-fluid">
            <div class="span12" style="margin-top:100px;">
                <div class="login-container">
                    <div class="row-fluid">
                        <div class="center">
                            <h1>
                                <i class="icon-leaf green"></i>
                                <span class="red">Aec</span>
                                <span class="white">砍价管理</span>
                            </h1>
                            <h4 class="blue">&copy; 武汉童梦健康管理有限公司</h4>
                        </div>
                    </div>
                    <div class="space-6"></div>
                    <div class="row-fluid">
                        <div class="position-relative">
                            <div id="login-box" class="login-box visible widget-box no-border">
                                <div class="widget-body">
                                    <div class="widget-main">
                                        <h4 class="header blue lighter bigger">
                                            <i class="icon-coffee green"></i>
                                            后台登录
                                        </h4>
                                        <div class="space-6"></div>
                                        <fieldset>
                                            <label>
                                                <span class="block input-icon input-icon-right">
                                                    <input type="text" id="username" class="span12" placeholder="Username"/>
                                                    <i class="icon-user"></i>
                                                </span>
                                            </label>
                                            <label>
                                                <span class="block input-icon input-icon-right">
                                                    <input type="password" id="password" class="span12" placeholder="Password"/>
                                                    <i class="icon-lock"></i>
                                                </span>
                                            </label>
                                            <div class="space"></div>
                                            <div class="clearfix">
                                                <label class="inline">
                                                    <input type="checkbox"/>
                                                    <span class="lbl"> Remember Me</span>
                                                </label>
                                                <button onclick="login()" class="width-35 pull-right btn btn-small btn-primary">
                                                    <i class="icon-key"></i>
                                                    登录
                                                </button>
                                            </div>
                                            <div class="space-4"></div>
                                        </fieldset>
                                    </div><!--/widget-main-->
                                </div><!--/widget-body-->
                            </div><!--/login-box-->
                        </div><!--/position-relative-->
                    </div>
                </div>
            </div><!--/.span-->
        </div><!--/.row-fluid-->
    </div>
</div><!--/.main-container-->
<!--basic scripts-->
<!--[if !IE]>-->
<script src="<?=constant('BASE_URL')?>/ace/assets/js/jquery-2.0.3.min.js"></script>
<!--<![endif]-->
<script src="<?=constant('BASE_URL')?>/ace/assets/js/bootstrap.min.js"></script>
<!--page specific plugin scripts-->
<!--ace scripts-->
<script src="<?=constant('BASE_URL')?>/ace/assets/js/ace-elements.min.js"></script>
<script src="<?=constant('BASE_URL')?>/ace/assets/js/ace.min.js"></script>
<script src="<?=constant('BASE_URL')?>/ace/assets/js/bootbox.min.js"></script>
<!--inline scripts related to this page-->
<script type="text/javascript">
    $(document).on("keydown",function (event) {
        var e = event || window.event ||arguments.callee.caller.arguments[0];
        if(e && e.keyCode==13){
            login();
        }
    });
    function login() {
        var username = $('#username').val();
        var password = $('#password').val();
        $.ajax({
            type: "POST",
            url: "/admin/login/login",
            data: {'username':username, 'password':password},
            success:function(res){
                if (res.code == 0) {
                    window.location.href = "<?=constant('BASE_URL')?>"+res.redirect;
                } else {
                    bootbox.dialog(res.message, [{
                            "label" : "确定",
                            "class" : "btn-small btn-danger",
                        }]
                    );
                }
            }
        });
    }
</script>
</body>
</html>
